; ENet Event Types
Const ENET_EVENT_TYPE_NONE       = 0
Const ENET_EVENT_TYPE_CONNECT    = 1
Const ENET_EVENT_TYPE_DISCONNECT = 2
Const ENET_EVENT_TYPE_RECEIVE    = 3

; ENet Packet Flags

Const ENET_PACKET_FLAG_UNRELIALE			  = 0
Const ENET_PACKET_FLAG_RELIABLE            = 1
Const ENET_PACKET_FLAG_UNSEQUENCED         = 2
Const ENET_PACKET_FLAG_UNRELIABLE_FRAGMENT = 8

Const ENET_PEER_STATE_DISCONNECTED          = 0
Const ENET_PEER_STATE_CONNECTING            = 1
Const ENET_PEER_STATE_ACKNOWLEDGING_CONNECT = 2
Const ENET_PEER_STATE_CONNECTION_PENDING    = 3
Const ENET_PEER_STATE_CONNECTION_SUCCEEDED  = 4
Const ENET_PEER_STATE_CONNECTED             = 5
Const ENET_PEER_STATE_DISCONNECT_LATER      = 6
Const ENET_PEER_STATE_DISCONNECTING         = 7
Const ENET_PEER_STATE_ACKNOWLEDGING_DISCONNECT = 8
Const ENET_PEER_STATE_ZOMBIE                = 9